language: python
python:
    - "3.6"
    
install:
    # Install impactutils and requirements
    - bash install.sh -r
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - conda activate impact
services:
    - xvfb
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - py.test --cov=impactutils
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
